version: 2.1
orbs:
  node: circleci/node@3.0.0
  sonarcloud: sonarsource/sonarcloud@1.0.2
workflows:
  node-tests:
    jobs:
      steps:
        - checkout
        - run: npm install
        - run:
            name: "Run Jest and Collect Coverage Reports"
            command: jest --collectCoverage=true
        - store_artifacts:
          path: coverage
