on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get master
      run: git fetch origin master
    - name: Install dependencies
      run:  npm install
    - name: Install Jest globally
      run:  sudo npm install -g jest
    - name: Run Tests
      run:  npm run test:ci
    - name: fix code coverage paths
      working-directory: ./coverage
      run: |
        sed -i 's/\/home\/runner\/work\/Some-test\/Some-test\//\/github\/workspace\//g' lcov.info
        sed -i 's/\/home\/runner\/work\/Some-test\/Some-test\//\/github\/workspace\//g' test-report.xml
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: reports/test-report.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
